version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - redis
    networks:
      - devnet

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - devnet

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - devnet

networks:
  devnet:

volumes:
  mongo_data:
