services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo/devsol
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: devsol_secret
      GOOGLE_AI_KEY: dummy_key
