name: Backend API Tests (Docker Compose)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to start..."
          until curl -s http://localhost:3000/healthcheck; do
            sleep 5
          done

      - name: Install Newman and HTML reporter
        run: npm install -g newman newman-reporter-html

      - name: Run Postman tests with Newman
        run: |
          newman run backend/postman/SOEN.postman_collection.json \
          -e backend/postman/SOEN.postman_environment.json \
          -r cli,html \
          --reporter-html-export newman-report.html

      - name: Upload Newman HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html


      - name: Tear down Docker containers
        run: docker-compose -f docker-compose.yml down
