name: CI - DevSol Postman Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Create backend .env file
        run: |
          cat <<EOF > backend/.env
          PORT=3000
          MONGODB_URI=mongodb://mongo/devsol
          JWT_SECRET=devsol_secret
          REDIS_HOST=redis
          REDIS_PORT=6379
          REDIS_PASSWORD=
          GOOGLE_AI_KEY=dummy_google_key
          EOF

      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..30}; do
            if curl -s http://localhost:3000/health; then
              echo "Backend is up!"
              break
            fi
            sleep 3
          done

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Tests
        run: |
          newman run backend/postman/SOEN.postman_collection.json \
            -e backend/postman/SOEN.postman_environment.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: Upload Newman HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html

