name: Backend API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start backend and dependencies
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for backend to be ready
        run: |
          for i in {1..60}; do
            if curl -s http://localhost:3000/health; then
              echo "Backend is ready"
              exit 0
            else
              echo "Waiting for backend to start..."
              sleep 1
            fi
          done
          echo "Backend failed to start within 60 seconds"
          exit 1

      - name: Run Newman API tests
        run: newman run backend/postman/SOEN.postman_collection.json -e backend/postman/SOEN.postman_environment.json
